server:
   port: 9191

spring: 
   datasource: 
      url: jdbc:postgresql://db.rndmzyexjwkaxmtrmfqb.supabase.co:5432/dev-soft
      username: postgres
      password: Fr12ju90.@142536

   jpa:
      properties:
         hibernate:
            dialect: org.hibernate.dialect.PostgreSQL95Dialect
            format_sql: false
            ddl-auto: none
            temp:
               use_jdbc_metadata_defaults: false
      show-sql: true